name: Build

on: [push]

jobs:
  build:
    env:
      IP: ${{ secrets.IP }}
      KEY: ${{ secrets.KEY }}
      PORT: ${{ secrets.PORT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configuration environment
        run: |
          mkdir -p ~/.ssh/
          echo "$KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 -p $PORT $IP >> ~/.ssh/known_hosts
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ryuuinc/kojinbot
          tags: latest
      - name: SSH stuff
        run: |
          ssh root@$IP -p $PORT "./docker_kojinbot.sh"
